[runner]
enforceSerializableSessionState = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"
